import type { Metadata } from 'next'
import '@/styles/globals.css'
import { geistSans } from '@/lib/fonts'
import type { ChildrenProps } from '@/types/utils'
import { cn } from '@/lib/utils'
import Header from '@/components/header'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Fragment } from 'react'

export const metadata: Metadata = {
  title: 'edwardribas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: ChildrenProps) {
  return (
    <html lang="en">
      <body className={cn(geistSans.className, 'bg-background')}>
        <ScrollArea className='h-dvh w-dvw'>
          <div className='w-dvw'>
            <Header />
            {children}
          </div>
        </ScrollArea>
      </body>
    </html>
  )
}
